In [1]:
import pandas as pd

**loading the dataset**

In [2]:
df = pd.read_csv(r"datasets/netflix_titles.csv")

#### understanding the dataset

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
df.shape

(7787, 12)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   str
 1   type          7787 non-null   str
 2   title         7787 non-null   str
 3   director      5398 non-null   str
 4   cast          7069 non-null   str
 5   country       7280 non-null   str
 6   date_added    7777 non-null   str
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   str
 9   duration      7787 non-null   str
 10  listed_in     7787 non-null   str
 11  description   7787 non-null   str
dtypes: int64(1), str(11)
memory usage: 730.2 KB

#### finding missing values

In [6]:
df.isna().any()

show_id         False
type            False
title           False
director         True
cast             True
country          True
date_added       True
release_year    False
rating           True
duration        False
listed_in       False
description     False
dtype: bool

**ranking columns based on missing values**

In [7]:
# Calculate the percentage of missing values per column and sort them descending
missing_percentage = df.isnull().mean() * 100
missing_ranked = missing_percentage.sort_values(ascending=False)

# Print the ranked list
print("--- Columns Ranked by Missingness (%) ---")
print(missing_ranked)

--- Columns Ranked by Missingness (%) ---
director        30.679337
cast             9.220496
country          6.510851
date_added       0.128419
rating           0.089893
title            0.000000
show_id          0.000000
type             0.000000
release_year     0.000000
duration         0.000000
listed_in        0.000000
description      0.000000
dtype: float64

### handling missing data

##### filling the director column
filling missing in director column with "unknown" because this column will help us deciding director's shows are going on trend

In [8]:
df["director"] = df["director"].fillna(value="unknown")

##### filling cast column
also filling this with unknown because it can also help us analyze which show can go on trend if have particular people in cast

In [9]:
df["cast"] = df["cast"].fillna(value="unknown")

##### dropping all the rows which have country null

In [10]:
df = df.dropna(subset=["country"])

##### dropping rating and date_added rows
because i want pristine dataset for modeling and don't want to introduce any artificial or duplicated dates/ratings.

In [11]:
df = df.dropna(subset=["rating", "date_added"])

##### seeing duplicates
some columns can have duplicate values because of many reason one of them may like many movie might be directed by one same director, like
- type
- director
- cast
- country 
- rating 
- duration
- listed_in

but some columns must be unique so that we can have distinction, like
- title
- description

In [12]:
df[df.duplicated(subset="duration", keep=False)].sort_values(by="duration")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3226,s3227,TV Show,JU-ON: Origins,unknown,"Yoshiyoshi Arakawa, Yuina Kuroshima, Ririka, K...",Japan,"July 3, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Horror, TV Mysteries",A paranormal researcher searches obsessively f...
4938,s4939,TV Show,Power Rangers Operation Overdrive,unknown,"James Maclurcan, Caitlin Murphy, Samuell Benta...","United States, New Zealand, Japan","January 1, 2016",2007,TV-Y7,1 Season,Kids' TV,To keep powerful jewels from falling into the ...
4937,s4938,TV Show,Power Rangers Ninja Storm,unknown,"Pua Magasiva, Sally Martin, Glenn McMillan, Ad...","United States, New Zealand","January 1, 2016",2003,TV-Y7,1 Season,Kids' TV,When the elite warriors from the Wind Ninja Ac...
4935,s4936,TV Show,Power Rangers Mystic Force,unknown,"Firass Dirani, Angie Diaz, Richard Brancatisan...",United States,"January 1, 2016",2006,TV-Y7,1 Season,Kids' TV,"When the wicked Undead Army is unleashed, sorc..."
1335,s1336,TV Show,Children of the Whales,unknown,"Natsuki Hanae, Manaka Iwami, Yuuichirou Umehar...",Japan,"March 13, 2018",2017,TV-14,1 Season,"Anime Series, International TV Shows","As a magic wielder, young archivist Chakuro kn..."
...,...,...,...,...,...,...,...,...,...,...,...,...
423,s424,Movie,"All's Well, End's Well (2009)",Vincent Kok,"Louis Koo, Sandra Ng Kwan Yue, Raymond Wong, R...",Hong Kong,"November 9, 2018",2009,TV-14,99 min,"Comedies, International Movies, Romantic Movies",Bound by a family rule that forbids him from m...
1293,s1294,Movie,Chasing Trane,John Scheinfeld,"Denzel Washington, Bill Clinton, Ravi Coltrane...",United States,"November 13, 2017",2016,TV-PG,99 min,"Documentaries, Music & Musicals","Featuring interviews, insights and archival fo..."
4039,s4040,Movie,Mercenary,Sacha Wolff,"Toki Pilioko, Iliana Zabeth, Mikaele Tuugahala...",France,"December 4, 2016",2016,TV-MA,99 min,"Dramas, International Movies, Sports Movies",When he defies his cruel father and leaves New...
4107,s4108,Movie,MindGamers,Andrew Goth,"Tom Payne, Melia Kreiling, Antonia Campbell-Hu...",Austria,"January 15, 2020",2017,R,99 min,"International Movies, Sci-Fi & Fantasy, Thrillers",Brilliant young students discover a breakthrou...
3622,s3623,Movie,Life 2.0,Jason Spingarn-Koff,unknown,United States,"April 1, 2017",2010,TV-MA,99 min,Documentaries,Computer users across the globe log onto the v...

In [13]:
df[df.duplicated()]   # <---- if nothing shows up means no duplicate row exist

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

##### Feature Understanding

In [14]:
df["country"].head(50)

0                             Brazil
1                             Mexico
2                          Singapore
3                      United States
4                      United States
5                             Turkey
6                              Egypt
7                      United States
8                              India
9                              India
10                     United States
11             Poland, United States
12                            Mexico
13                          Thailand
14                     United States
15                           Nigeria
17    Norway, Iceland, United States
18                             India
19                    United Kingdom
20                             India
21                             India
22                             India
23                             India
24                             Japan
25                     United States
26                     United States
27                       South Korea
28                             Italy
29                     United States
30                            Canada
31                         Indonesia
32                         Indonesia
33                     United States
34                            Canada
35                     United States
36                           Romania
37                           Romania
39                             Spain
40                            Turkey
41                           Iceland
42                            Turkey
43                           Nigeria
44                     United States
45                            Turkey
46                     United States
47                     United States
48             South Africa, Nigeria
49                            France
50       United States, South Africa
51                       South Korea
Name: country, dtype: str

#### Univariate Analysis

##### analyzing type column
In **type column**
movies are more common than TV shows

In [22]:
df[df["type"].str.contains("Movie")]["type"].count()

np.int64(5143)

##### analyzing rating column
checking which type of audience Netflix target more based on the rating according to the given dataset

In [159]:
# All Younger children under 7
df[
    df["rating"].isin(["TV-Y", "TV-G", "G"])
]["rating"].count()

np.int64(426)

In [160]:
# children above 7+ 
df[
    df["rating"].isin(["PG", "TV-Y7"])
]["rating"].count()

np.int64(464)

In [161]:
# older children 10+
df[
    df["rating"].isin(["TV-Y7-FV", "TV-PG"])
]["rating"].count()

np.int64(744)

In [162]:
# teens 13+
df[
    df["rating"].isin(["PG-13", "TV-14"])
]["rating"].count()

np.int64(2175)

In [163]:
# older teens 16+ & adults 18+
df[
    df["rating"].isin(["TV-MA", "R", "NC-17"])
]["rating"].count()

np.int64(3368)

In [165]:
# for all ages
df[
    df["rating"].isin(["UR"])
]["rating"].count()

np.int64(5)

In [168]:
# not rated 
df[
    df["rating"].isin(["NR"])
]["rating"].count()

np.int64(83)